name: cdcat-catalog
base: core18
version: '1.8'
summary: Media catalog program
description: |
  CDCat is a graphical, multiplatform media catalog program which scans the
  directories/drives you specify and makes a list of the filesystem
  contents (including the tags of MP3 files) and stores the result in a
  gzipped XML file.

grade: stable
confinement: strict

layout:
  /etc/fonts:
    bind: $SNAP/etc/fonts

parts:
  cdcat-catalog:
    plugin: nil
    override-build: |
      snapcraftctl build
      cd $SNAPCRAFT_PART_INSTALL/usr/bin/
      ln -s cdcat cdcat-catalog
    stage-packages:
      - cdcat
      - fontconfig-config
apps:
  cdcat-catalog:
    command: cdcat-catalog
    environment:
      XDG_DATA_HOME: $SNAP/usr/share
      FONTCONFIG_PATH: $SNAP/etc/fonts/conf.d
      FONTCONFIG_FILE: $SNAP/etc/fonts/fonts.conf
    plugs:
      - x11
      - home
      - removable-media