name: cdcat-catalog # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '1.8' # just for humans, typically '1.2+git' or '1.3.2'
summary: Media catalog program # 79 char long summary
description: |
  CDCat is a graphical, multiplatform media catalog program which scans the
  directories/drives you specify and makes a list of the filesystem
  contents (including the tags of MP3 files) and stores the result in a
  gzipped XML file.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

parts:
  cdcat-catalog:
    plugin: nil
    override-build: |
      snapcraftctl build
      cd $SNAPCRAFT_PART_INSTALL/usr/bin/
      ln -s cdcat cdcat-catalog
    stage-packages:
      - cdcat
      - fontconfig-config
apps:
  cdcat-catalog:
    command: cdcat-catalog
    environment:
      XDG_DATA_HOME: $SNAP/usr/share
      FONTCONFIG_PATH: $SNAP/etc/fonts/conf.d
      FONTCONFIG_FILE: $SNAP/etc/fonts/fonts.conf
    plugs:
      - x11